import metadata from '../../metadata.json';

// Full Devanagari Hindi translation of metadata.json's `content` object.
// Typed against the English shape so a missing/renamed field fails tsc
// instead of silently falling back to English at runtime.
export const hiContent: typeof metadata.content = {
  navLinks: [
    { name: 'होम', href: '#home' },
    { name: 'हमारे बारे में', href: '#about' },
    { name: 'सेवाएं', href: '#experience' },
    { name: 'प्रोजेक्ट्स', href: '#projects' },
    { name: 'संपर्क करें', href: '#contact' },
  ],
  nav: {
    ariaGithub: 'GitHub',
    ariaLinkedin: 'LinkedIn',
    ariaOpenMenu: 'मेनू खोलें',
    ariaCloseMenu: 'मेनू बंद करें',
    ariaLanguage: 'भाषा',
    langEnglishNative: 'English',
    langHindiNative: 'हिन्दी',
    langHindiGloss: 'Hindi',
    langEnglishGloss: 'अंग्रेज़ी',
  },
  techStack: metadata.content.techStack,
  services: [
    {
      title: 'बिज़नेस वेबसाइट',
      description: 'एक प्रोफेशनल, मोबाइल-फ्रेंडली वेबसाइट जिससे ग्राहकों को आपको ढूंढना, आपकी सेवाएं देखना और आपसे संपर्क करना आसान हो जाता है — उसी तरीके से बनी हुई जैसे हम बड़े प्लेटफ़ॉर्म बनाते हैं, React और Angular के साथ।',
      highlights: ['मोबाइल-फ्रेंडली डिज़ाइन', 'तेज़ लोडिंग स्पीड', 'आसानी से अपडेट करने योग्य'],
    },
    {
      title: 'ऑनलाइन बुकिंग और ऑर्डरिंग सिस्टम',
      description: 'ग्राहकों को कॉल करने के बजाय ऑनलाइन अपॉइंटमेंट बुक करने या ऑर्डर देने की सुविधा दें — एक ऐसे सिंपल सिस्टम के साथ जिसे आप खुद आसानी से मैनेज कर सकते हैं।',
      highlights: ['अपॉइंटमेंट और टेबल बुकिंग', 'ऑनलाइन ऑर्डरिंग', 'सिंपल एडमिन डैशबोर्ड'],
    },
    {
      title: 'मैनुअल काम का ऑटोमेशन',
      description: 'अगर आपकी टीम रोज़ एक जैसा डेटा दोबारा भर रही है, कागज़ी काम के पीछे भाग रही है, या रोज़ वही सवालों के जवाब दे रही है, तो हम आपके लिए ऐसा सिस्टम बना सकते हैं जो यह काम खुद कर दे — जहां ज़रूरत हो वहां AI के साथ भी।',
      highlights: ['डॉक्यूमेंट और फॉर्म ऑटोमेशन', 'AI-सहायित वर्कफ़्लो', 'कम दोहराए जाने वाले काम'],
    },
    {
      title: 'लोकल SEO और गूगल विज़िबिलिटी',
      description: 'जब आपके आस-पास कोई आपकी सेवा खोजे, तो आपकी वेबसाइट सामने आए — सही गूगल बिज़नेस सेटअप, तेज़ लोड होने वाली साइट, और सर्च इंजन के हिसाब से बनाए गए पेज।',
      highlights: ['गूगल बिज़नेस सेटअप', 'लोकल सर्च विज़िबिलिटी', 'साइट स्पीड और स्ट्रक्चर'],
    },
  ],
  projects: [
    {
      title: 'NGO Website',
      description: 'एक नॉन-प्रॉफिट संस्था की डिजिटल उपस्थिति बढ़ाने के लिए हाई-रेस्पॉन्सिव और SEO-फ्रेंडली प्लेटफ़ॉर्म।',
      tags: ['React', 'Tailwind', 'SEO'],
      metrics: [{ label: 'SEO स्कोर', value: '100' }],
      link: 'https://www.rashtriyaswasthyasangathan.org/',
    },
    {
      title: 'HRMS System',
      description: 'एंटरप्राइज़ उपयोग के लिए 25 से अधिक इंटीग्रेटेड मॉड्यूल्स वाला व्यापक ह्यूमन रिसोर्स मैनेजमेंट सिस्टम।',
      tags: ['MEAN Stack', 'Microservices', 'Redis'],
      metrics: [{ label: 'मॉड्यूल्स', value: '25+' }],
      link: 'https://arpit-dwivedi-dev.github.io/HRMS/',
    },
    {
      title: 'ROR Document System',
      subtitle: 'हेल्थकेयर AI प्लेटफ़ॉर्म',
      description: 'हेल्थकेयर सेक्टर के लिए एक प्रमुख AI-संचालित डॉक्यूमेंट मैनेजमेंट सिस्टम, जो बड़े PDF डेटासेट को बेहद कुशलता से संभालता है।',
      metrics: [
        { label: 'PDF पेजेस', value: '20,000+' },
        { label: 'परफॉर्मेंस', value: '99.9% ↑' },
        { label: 'ऑटोमेशन', value: '95%' },
      ],
      tags: ['Angular', 'Node.js', 'OCR', 'AI', 'Performance'],
      featured: true,
    },
    {
      title: 'QME Panel',
      description: 'हेल्थकेयर एनालिटिक्स डैशबोर्ड जो मेडिकल इवैल्यूएशन और पैनल मैनेजमेंट की गहरी जानकारी देता है।',
      tags: ['Angular', 'Node.js', 'D3.js', 'MongoDB'],
      metrics: [{ label: 'मॉड्यूल्स', value: '10+' }],
    },
  ],
  impactMetrics: [
    { label: 'PDF लोड ऑप्टिमाइज़ेशन', value: '99.9%' },
    { label: 'AI ऑटोमेशन', value: '95%' },
    { label: 'डिलीवर किए गए मॉड्यूल्स', value: '15+' },
    { label: 'टीम साइज़', value: '3 सदस्य' },
    { label: 'लागत बचत', value: '₹10–15L' },
  ],
  hero: {
    badge: '2021 से स्थानीय व्यवसायों की मदद कर रहे हैं',
    title: 'ज़्यादा ग्राहक पाएं।\nज़्यादा बुकिंग पाएं।',
    titleAccent: 'कम झंझट।',
    subtitle: 'स्थानीय व्यवसायों के लिए प्रोफेशनल वेबसाइट, ऑनलाइन बुकिंग, ऑर्डरिंग सिस्टम और ऑटोमेशन।',
    buttons: {
      projects: 'प्रोजेक्ट्स देखें',
      contact: 'कोटेशन पाएं',
    },
    stats: [
      { value: '4+', label: 'वर्षों का अनुभव' },
      { value: '15+', label: 'डिलीवर किए गए प्रोजेक्ट्स' },
    ],
    terminal: {
      filename: '101_tech_labs -- portfolio_v2.ts',
      code: {
        name: '101 Tech Labs',
        role: 'फुल-स्टैक और AI इंजीनियरिंग',
        stack: ['MEAN', 'AI', 'DevOps'],
        mission: 'स्केलेबल सिस्टम बनाना',
      },
      systemLoad: 'सिस्टम लोड',
      welcomeLine1: '101 Tech Labs टर्मिनल v2.0.0 में आपका स्वागत है',
      welcomeLine2: 'उपलब्ध कमांड देखने के लिए "help" टाइप करें।',
      inputPlaceholder: 'कमांड टाइप करें...',
      cleared: 'टर्मिनल साफ़ हो गया।',
      notFound: 'कमांड नहीं मिला: {cmd}. कमांड की सूची देखने के लिए "help" टाइप करें।',
      ariaInteractiveTerminal: 'इंटरैक्टिव टर्मिनल',
      ariaSendCommand: 'कमांड भेजें',
    },
    terminalCommands: {
      about: '101 Tech Labs स्थानीय व्यवसायों के लिए वेबसाइट, बुकिंग सिस्टम और ऑटोमेशन बनाता है — और ज़रूरत पड़ने पर हेल्थकेयर व एंटरप्राइज़ क्लाइंट्स के लिए बड़े प्लेटफ़ॉर्म भी।',
      skills: 'स्टैक: Angular, React, Node.js, Express, MongoDB, TypeScript, AI/LLMs, Docker, AWS.',
      projects: 'मुख्य प्रोजेक्ट: फ्लैगशिप OCR इंजन (ROR Document System)। साथ ही: QME Panel, HRMS System, NGO Platform.',
      contact: 'ईमेल: 101techlabs@gmail.com | GitHub: @101techlabs | वेब: 101techlabs.com',
      whoami: '101 Tech Labs — फुल-स्टैक और AI इंजीनियरिंग टीम, 2021 से स्थानीय व्यवसायों को ऑनलाइन लाने में मदद कर रही है।',
      location: 'दुनियाभर के क्लाइंट्स की सेवा करते हैं, रिमोट-फर्स्ट।',
      help: 'उपलब्ध कमांड: [about, skills, projects, contact, whoami, location, clear, exit]',
      exit: 'सेफ मोड सक्रिय। फिर से शुरू करने के लिए अपना टर्मिनल सेशन रीफ़्रेश करें।',
    },
  },
  about: {
    label: 'हम कौन हैं',
    title: 'हमारे',
    titleAccent: 'बारे में',
    paragraphs: [
      'हम **स्थानीय व्यवसायों** के लिए वेबसाइट, बुकिंग सिस्टम, और रोज़मर्रा का ऑटोमेशन बनाते हैं — दुकानों, रेस्टोरेंट्स, क्लीनिक्स, और सर्विस प्रोवाइडर्स के लिए, जिन्हें पूरी IT टीम रखे बिना एक प्रोफेशनल ऑनलाइन पहचान चाहिए।',
      'हम **हेल्थकेयर और एंटरप्राइज़ क्लाइंट्स** के लिए भी बड़े सिस्टम बनाते हैं — डॉक्यूमेंट प्रोसेसिंग प्लेटफ़ॉर्म, HR सिस्टम, शेड्यूलिंग सॉफ़्टवेयर। इस अनुभव का मतलब है कि आपके बिज़नेस को चाहे पाँच पेज की वेबसाइट चाहिए हो या कस्टम बुकिंग सिस्टम, हम इससे कहीं मुश्किल समस्याएं पहले ही हल कर चुके हैं।',
      'हम चीज़ों को सरल रखते हैं: स्पष्ट जवाब, उचित कीमत, और एक ऐसी वेबसाइट या सिस्टम जो वाकई इस्तेमाल हो — कोई ऐसा टेक्निकल शोकेस नहीं जो किसी ने माँगा ही न हो।',
    ],
    features: ['तेज़ पेज स्पीड', 'सुरक्षित और भरोसेमंद', 'हमेशा चालू होस्टिंग', 'आसानी से मैनेज करें'],
    card: {
      est: 'स्थापना 2021',
      location: 'दुनियाभर में व्यवसायों की सेवा',
      locationLabel: 'सेवा क्षेत्र',
      expertise: [
        { title: 'वेबसाइट और सिस्टम', subtitle: 'लंबे समय तक चलने के लिए बने' },
        { title: 'AI और ऑटोमेशन', subtitle: 'जहां यह वाकई मदद करता है' },
      ],
    },
  },
  techStackSection: {
    label: 'टेक्निकल आर्सेनल',
    title: 'टेक',
    titleAccent: 'स्टैक',
    categories: {
      frontend: 'फ्रंटएंड',
      backend: 'बैकएंड',
      database: 'डेटाबेस',
      devops: 'DevOps',
    },
  },
  devops: {
    label: 'इंफ्रास्ट्रक्चर',
    title: 'DevOps और',
    titleAccent: 'आर्किटेक्चर',
    description: 'हम ऐसे CI/CD पाइपलाइन और कंटेनराइज़्ड एनवायरनमेंट बनाते हैं जिससे डिप्लॉयमेंट उबाऊ हो जाए — कोई सरप्राइज़ नहीं, कोई मैन्युअल स्टेप नहीं, कोई अनप्लांड डाउनटाइम नहीं। इनकमिंग ट्रैफ़िक को कई ऐप सर्वरों में लोड-बैलेंस किया जाता है, जो सभी एक शेयर्ड डेटाबेस क्लस्टर पर आधारित होते हैं।',
    list: ['Docker कंटेनराइज़ेशन', 'GitHub Actions CI/CD', 'VPS होस्टिंग और Nginx कॉन्फ़िगरेशन'],
  },
  localTrust: {
    label: 'स्थानीय व्यवसायों की सेवा',
    title: 'बनाया गया',
    titleAccent: 'आपके मोहल्ले के लिए',
    description: 'हम सिर्फ देशभर के एंटरप्राइज़ क्लाइंट्स के साथ नहीं, बल्कि आपके आस-पास के व्यवसायों के साथ भी काम करते हैं।',
    phone: '+91 70715 20965',
    serviceArea: 'दुनियाभर में व्यवसायों की सेवा',
    callLabel: 'हमें कॉल करें',
    serviceAreaLabel: 'सेवा क्षेत्र',
    testimonials: [
      { quote: 'इन्होंने एक हफ्ते में हमारा बुकिंग सिस्टम बना दिया, और टेबल की उपलब्धता पूछने वाली कॉल्स लगभग बंद हो गईं।', name: 'प्रिया नायर', business: 'कॉपर केटल कैफ़े' },
      { quote: 'फेसबुक पेज से एक असली वेबसाइट और ऑनलाइन अपॉइंटमेंट तक — पूरी प्रक्रिया सीधी थी, कोई तकनीकी उलझन नहीं।', name: 'रोहन मेहता', business: 'मेहता डेंटल क्लीनिक' },
    ],
  },
  contact: {
    label: 'संपर्क करें',
    title: 'आइए कुछ ऐसा बनाएं',
    titleAccent: 'जो असर डाले',
    description: 'हम नए प्रोजेक्ट्स, तकनीकी चुनौतियों, या ऐसे काम पर चर्चा के लिए तैयार हैं जिसमें एक व्यक्ति के बजाय एक पूरी फुल-स्टैक टीम की ज़रूरत हो।',
    email: '101techlabs@gmail.com',
    linkedin: '101 Tech Labs',
    linkedinUrl: 'https://www.linkedin.com/company/133407777/',
    github: '101techlabs',
    whatsapp: {
      number: '917071520965',
      message: 'नमस्ते 101 Tech Labs',
    },
    whatsappLabel: 'WhatsApp पर हमसे चैट करें',
    mailSubjectTemplate: '{name} की ओर से नई प्रोजेक्ट पूछताछ',
    statusSent: 'मैसेज भेज दिया गया है — हम जल्द ही आपसे संपर्क करेंगे।',
    statusError: 'कुछ गड़बड़ हो गई। कृपया हमें सीधे {email} पर ईमेल करें।',
    form: {
      name: 'नाम',
      email: 'ईमेल',
      message: 'मैसेज',
      button: 'मैसेज भेजें',
      sending: 'भेजा जा रहा है...',
      namePlaceholder: 'आपका नाम',
      emailPlaceholder: 'your@email.com',
      messagePlaceholder: 'अपने प्रोजेक्ट के बारे में बताएं...',
      errors: {
        nameRequired: 'कृपया अपना नाम दर्ज करें।',
        emailRequired: 'कृपया अपना ईमेल दर्ज करें।',
        emailInvalid: 'कृपया एक सही ईमेल पता दर्ज करें।',
        messageRequired: 'कृपया एक मैसेज दर्ज करें।',
      },
    },
  },
  featuredProject: {
    label: 'हम क्या संभाल सकते हैं',
    title: 'बनाया गया',
    titleAccent: 'गंभीर जटिलता के लिए',
    description: 'यह उस तरह की तकनीकी जटिलता है जिसे हम एंटरप्राइज़ क्लाइंट्स के लिए संभालते हैं — और इसीलिए आपकी बिज़नेस वेबसाइट या बुकिंग सिस्टम बनाना हमारे लिए बिल्कुल आसान है।',
    button: 'केस स्टडी देखें',
    visual: {
      ocr: 'OCR इंजन',
      ai: 'AI पार्सर',
      badge: '99.9% ऑप्टिमाइज़्ड',
    },
  },
  servicesSection: {
    label: 'हम कैसे मदद करते हैं',
    title: 'हम क्या',
    titleAccent: 'करते हैं',
  },
  projectsSection: {
    label: 'पोर्टफोलियो',
    title: 'प्रमुख',
    titleAccent: 'प्रोजेक्ट्स',
    description: 'एंटरप्राइज़-स्तर के सिस्टम जो हमने डिलीवर किए हैं — यह साबित करते हुए कि आपके प्रोजेक्ट को चाहे जो भी जटिलता चाहिए, हम उससे कठिन काम पहले ही संभाल चुके हैं।',
    pageTitle: 'सभी',
    pageTitleAccent: 'प्रोजेक्ट्स',
    pageDescription: 'हमारे इंजीनियरिंग काम का पूरा कलेक्शन देखें — प्रोडक्शन सिस्टम, प्लेटफ़ॉर्म, और टेक्निकल एक्सपेरिमेंट्स।',
    backToHome: 'होम पर वापस जाएं',
    viewAll: 'सभी प्रोजेक्ट्स देखें',
  },
  projectCard: {
    viewGithub: 'GitHub रिपॉज़िटरी देखें',
    viewLive: 'लाइव प्रोजेक्ट देखें',
    viewDetails: '{title} प्रोजेक्ट का विवरण देखें',
  },
  achievementsSection: {
    label: 'इम्पैक्ट मेट्रिक्स',
    title: 'रियल-वर्ल्ड',
    titleAccent: 'इम्पैक्ट',
  },
  architecture: {
    loadBalancer: 'लोड बैलेंसर (NGINX)',
    nodeApp: 'नोड ऐप',
    database: 'MongoDB क्लस्टर',
  },
  footer: {
    rights: 'सर्वाधिकार सुरक्षित।',
    techNote: 'आधुनिक, भरोसेमंद तकनीक पर बना।',
  },
};
