import {defineType, defineField} from 'sanity'

const ls = {type: 'localeString'}
const lt = {type: 'localeText'}

export const siteContent = defineType({
  name: 'siteContent',
  title: 'Site Content',
  type: 'document',
  // Singleton: the Studio structure (see structure.ts) only ever links to one
  // document with this fixed id, so editors can't accidentally create a second.
  fields: [
    defineField({name: 'navLinks', title: 'Nav Links', type: 'array', of: [{type: 'navLink'}]}),
    defineField({
      name: 'nav',
      title: 'Nav (aria labels & language switcher)',
      type: 'object',
      fields: [
        defineField({name: 'ariaGithub', title: 'Aria: GitHub', ...ls}),
        defineField({name: 'ariaLinkedin', title: 'Aria: LinkedIn', ...ls}),
        defineField({name: 'ariaOpenMenu', title: 'Aria: Open menu', ...ls}),
        defineField({name: 'ariaCloseMenu', title: 'Aria: Close menu', ...ls}),
        defineField({name: 'ariaLanguage', title: 'Aria: Language switcher group', ...ls}),
        defineField({name: 'langEnglishNative', title: 'English (native label)', ...ls}),
        defineField({name: 'langHindiNative', title: 'Hindi (native label)', ...ls}),
        defineField({name: 'langHindiGloss', title: 'Hindi gloss', ...ls}),
        defineField({name: 'langEnglishGloss', title: 'English gloss', ...ls}),
      ],
    }),
    defineField({
      name: 'techStack',
      title: 'Tech Stack (proper nouns, not translated)',
      type: 'object',
      fields: [
        defineField({name: 'frontend', title: 'Frontend', type: 'array', of: [{type: 'string'}]}),
        defineField({name: 'backend', title: 'Backend', type: 'array', of: [{type: 'string'}]}),
        defineField({name: 'database', title: 'Database', type: 'array', of: [{type: 'string'}]}),
        defineField({name: 'devops', title: 'DevOps', type: 'array', of: [{type: 'string'}]}),
        defineField({name: 'testing', title: 'Testing', type: 'array', of: [{type: 'string'}]}),
      ],
    }),
    defineField({name: 'services', title: 'Services', type: 'array', of: [{type: 'serviceItem'}]}),
    defineField({name: 'projects', title: 'Projects', type: 'array', of: [{type: 'projectItem'}]}),
    defineField({name: 'impactMetrics', title: 'Impact Metrics (currently unused on-page)', type: 'array', of: [{type: 'statPair'}]}),
    defineField({
      name: 'hero',
      title: 'Hero',
      type: 'object',
      fields: [
        defineField({name: 'badge', title: 'Badge', ...ls}),
        defineField({name: 'title', title: 'Title (supports line breaks)', ...lt}),
        defineField({name: 'titleAccent', title: 'Title Accent', ...ls}),
        defineField({name: 'subtitle', title: 'Subtitle', ...lt}),
        defineField({
          name: 'buttons',
          type: 'object',
          fields: [
            defineField({name: 'projects', title: 'Projects button', ...ls}),
            defineField({name: 'contact', title: 'Contact button', ...ls}),
          ],
        }),
        defineField({name: 'stats', title: 'Stats', type: 'array', of: [{type: 'statPair'}]}),
        defineField({
          name: 'terminal',
          title: 'Terminal UI',
          type: 'object',
          fields: [
            defineField({name: 'filename', title: 'Filename (not translated)', type: 'string'}),
            defineField({
              name: 'code',
              type: 'object',
              fields: [
                defineField({name: 'name', title: 'Name (not translated)', type: 'string'}),
                defineField({name: 'role', title: 'Role', ...ls}),
                defineField({name: 'stack', title: 'Stack (not translated)', type: 'array', of: [{type: 'string'}]}),
                defineField({name: 'mission', title: 'Mission', ...ls}),
              ],
            }),
            defineField({name: 'systemLoad', title: 'System Load label', ...ls}),
            defineField({name: 'welcomeLine1', title: 'Welcome line 1', ...ls}),
            defineField({name: 'welcomeLine2', title: 'Welcome line 2', ...ls}),
            defineField({name: 'inputPlaceholder', title: 'Input placeholder', ...ls}),
            defineField({name: 'cleared', title: '"clear" command output', ...ls}),
            defineField({name: 'notFound', title: 'Command-not-found (use {cmd} token)', ...ls}),
            defineField({name: 'ariaInteractiveTerminal', title: 'Aria: interactive terminal', ...ls}),
            defineField({name: 'ariaSendCommand', title: 'Aria: send command', ...ls}),
          ],
        }),
        defineField({
          name: 'terminalCommands',
          title: 'Terminal Commands',
          type: 'object',
          fields: [
            defineField({name: 'about', ...lt}),
            defineField({name: 'skills', ...lt}),
            defineField({name: 'projects', ...lt}),
            defineField({name: 'contact', ...lt}),
            defineField({name: 'whoami', ...lt}),
            defineField({name: 'location', ...lt}),
            defineField({name: 'help', ...lt}),
            defineField({name: 'exit', ...lt}),
          ],
        }),
      ],
    }),
    defineField({
      name: 'about',
      title: 'About',
      type: 'object',
      fields: [
        defineField({name: 'label', ...ls}),
        defineField({name: 'title', ...ls}),
        defineField({name: 'titleAccent', ...ls}),
        defineField({
          name: 'paragraphs',
          title: 'Paragraphs (wrap highlighted phrases in **like this**)',
          type: 'array',
          of: [{type: 'localeText'}],
        }),
        defineField({name: 'features', title: 'Features', type: 'array', of: [{type: 'localeString'}]}),
        defineField({
          name: 'card',
          type: 'object',
          fields: [
            defineField({name: 'est', title: 'Established label', ...ls}),
            defineField({name: 'location', ...ls}),
            defineField({name: 'locationLabel', ...ls}),
            defineField({name: 'expertise', type: 'array', of: [{type: 'expertiseItem'}]}),
          ],
        }),
      ],
    }),
    defineField({
      name: 'techStackSection',
      title: 'Tech Stack Section',
      type: 'object',
      fields: [
        defineField({name: 'label', ...ls}),
        defineField({name: 'title', ...ls}),
        defineField({name: 'titleAccent', ...ls}),
        defineField({
          name: 'categories',
          type: 'object',
          fields: [
            defineField({name: 'frontend', ...ls}),
            defineField({name: 'backend', ...ls}),
            defineField({name: 'database', ...ls}),
            defineField({name: 'devops', ...ls}),
          ],
        }),
      ],
    }),
    defineField({
      name: 'devops',
      title: 'DevOps & Architecture Section',
      type: 'object',
      fields: [
        defineField({name: 'label', ...ls}),
        defineField({name: 'title', ...ls}),
        defineField({name: 'titleAccent', ...ls}),
        defineField({name: 'description', ...lt}),
        defineField({name: 'list', type: 'array', of: [{type: 'localeString'}]}),
      ],
    }),
    defineField({
      name: 'localTrust',
      title: 'Local Trust Section',
      type: 'object',
      fields: [
        defineField({name: 'label', ...ls}),
        defineField({name: 'title', ...ls}),
        defineField({name: 'titleAccent', ...ls}),
        defineField({name: 'description', ...lt}),
        defineField({name: 'phone', title: 'Phone (not translated)', type: 'string'}),
        defineField({name: 'serviceArea', ...ls}),
        defineField({name: 'callLabel', ...ls}),
        defineField({name: 'serviceAreaLabel', ...ls}),
        defineField({name: 'testimonials', type: 'array', of: [{type: 'testimonialItem'}]}),
      ],
    }),
    defineField({
      name: 'contact',
      title: 'Contact Section',
      type: 'object',
      fields: [
        defineField({name: 'label', ...ls}),
        defineField({name: 'title', ...ls}),
        defineField({name: 'titleAccent', ...ls}),
        defineField({name: 'description', ...lt}),
        defineField({name: 'email', title: 'Email (not translated)', type: 'string'}),
        defineField({name: 'linkedin', title: 'LinkedIn handle (not translated)', type: 'string'}),
        defineField({name: 'github', title: 'GitHub handle (not translated)', type: 'string'}),
        defineField({
          name: 'whatsapp',
          type: 'object',
          fields: [
            defineField({name: 'number', title: 'Number (not translated)', type: 'string'}),
            defineField({name: 'message', title: 'Pre-filled message', ...ls}),
          ],
        }),
        defineField({name: 'whatsappLabel', title: 'Aria: WhatsApp button', ...ls}),
        defineField({name: 'mailSubjectTemplate', title: 'Mail subject (use {name} token)', ...ls}),
        defineField({name: 'statusSent', title: 'Status: sent', ...ls}),
        defineField({name: 'statusError', title: 'Status: error (use {email} token)', ...ls}),
        defineField({
          name: 'form',
          type: 'object',
          fields: [
            defineField({name: 'name', title: 'Name label', ...ls}),
            defineField({name: 'email', title: 'Email label', ...ls}),
            defineField({name: 'message', title: 'Message label', ...ls}),
            defineField({name: 'button', title: 'Submit button', ...ls}),
            defineField({name: 'sending', title: 'Submit button (sending state)', ...ls}),
            defineField({name: 'namePlaceholder', ...ls}),
            defineField({name: 'emailPlaceholder', ...ls}),
            defineField({name: 'messagePlaceholder', ...ls}),
            defineField({
              name: 'errors',
              type: 'object',
              fields: [
                defineField({name: 'nameRequired', ...ls}),
                defineField({name: 'emailRequired', ...ls}),
                defineField({name: 'emailInvalid', ...ls}),
                defineField({name: 'messageRequired', ...ls}),
              ],
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: 'featuredProject',
      title: 'Featured Project Section',
      type: 'object',
      fields: [
        defineField({name: 'label', ...ls}),
        defineField({name: 'title', ...ls}),
        defineField({name: 'titleAccent', ...ls}),
        defineField({name: 'description', ...lt}),
        defineField({name: 'button', ...ls}),
        defineField({
          name: 'visual',
          type: 'object',
          fields: [
            defineField({name: 'ocr', ...ls}),
            defineField({name: 'ai', ...ls}),
            defineField({name: 'badge', ...ls}),
          ],
        }),
      ],
    }),
    defineField({
      name: 'servicesSection',
      title: 'Services Section',
      type: 'object',
      fields: [
        defineField({name: 'label', ...ls}),
        defineField({name: 'title', ...ls}),
        defineField({name: 'titleAccent', ...ls}),
      ],
    }),
    defineField({
      name: 'projectsSection',
      title: 'Projects Section',
      type: 'object',
      fields: [
        defineField({name: 'label', ...ls}),
        defineField({name: 'title', ...ls}),
        defineField({name: 'titleAccent', ...ls}),
        defineField({name: 'description', ...lt}),
        defineField({name: 'pageTitle', ...ls}),
        defineField({name: 'pageTitleAccent', ...ls}),
        defineField({name: 'pageDescription', ...lt}),
        defineField({name: 'backToHome', ...ls}),
        defineField({name: 'viewAll', ...ls}),
      ],
    }),
    defineField({
      name: 'projectCard',
      title: 'Project Card (aria labels)',
      type: 'object',
      fields: [
        defineField({name: 'viewGithub', ...ls}),
        defineField({name: 'viewLive', ...ls}),
        defineField({name: 'viewDetails', title: 'View details (use {title} token)', ...ls}),
      ],
    }),
    defineField({
      name: 'achievementsSection',
      title: 'Achievements Section (currently unused on-page)',
      type: 'object',
      fields: [
        defineField({name: 'label', ...ls}),
        defineField({name: 'title', ...ls}),
        defineField({name: 'titleAccent', ...ls}),
      ],
    }),
    defineField({
      name: 'architecture',
      title: 'Architecture Diagram Labels',
      type: 'object',
      fields: [
        defineField({name: 'loadBalancer', ...ls}),
        defineField({name: 'nodeApp', ...ls}),
        defineField({name: 'database', ...ls}),
      ],
    }),
    defineField({
      name: 'footer',
      title: 'Footer',
      type: 'object',
      fields: [
        defineField({name: 'rights', ...ls}),
        defineField({name: 'techNote', ...ls}),
      ],
    }),
  ],
  preview: {
    prepare: () => ({title: '101 Tech Labs — Site Content'}),
  },
})
